version: "2"
services:
  service-registry:
    image: clarketm/service-registry
    environment:
      SERVICE_HOST: registry
      SERVICE_PORT: 8761

  uaa-service:
    image: clarketm/uaa-service
    environment:
      SERVICE_PORT: 8769
      REGISTRY_URL: http://service-registry:8761/eureka
    links:
      - service-registry:service-registry

  api-gateway:
    image: clarketm/api-gateway
    environment:
      SERVICE_PORT: 8765
      REGISTRY_URL: http://service-registry:8761/eureka
    ports:
      - 8765:8765
    links:
      - service-registry:service-registry
      - uaa-service:uaa-service

  dummy-service:
    image: clarketm/dummy-service
    environment:
      SERVICE_PORT: 8870
      REGISTRY_URL: http://service-registry:8761/eureka
    links:
      - service-registry:service-registry
      - uaa-service:uaa-service

